Add common components
gumgum/gumdrops pull request #104
Opened 2022-04-25 18:06 UTC by morganee

Add 2 properties to Modal
Add new component FormInputWrapper that mimic the "ValidXX" ones that we have to be generic
Add Icon, TooltipIcon, TablePaginationFooter, Tabs
Updates design system version

2022-04-26 04:39 UTC, mnicole commented
thanks for the updates!! :) 
just had a few comments.. the main one is the build is failing since gumdrops doesn't have a dependency on react router

2022-04-26 04:39 UTC, mnicole commented
oh also, i think you need to import the new components in components/index.js too to have them build properly when we build the library

2022-04-26 11:21 UTC, morganee commented
> oh also, i think you need to import the new components in components/index.js too to have them build properly when we build the library

It fixed it ! thanks. I removed the <Link> option in the Tabs component too, to remove the react-router-dom dependency, we can use the onclick function and it's cleaner I think

2022-04-27 18:16 UTC, mnicole commented
thanks, the branch built now! are you going to address the other comments too? :)

2022-04-27 19:18 UTC, morganee commented
> thanks, the branch built now! are you going to address the other comments too? :)

Have I missed one ? I'm only seeing the one about the react-router which I removed

2022-04-27 19:21 UTC, mnicole requested changes

2022-04-27 19:22 UTC, mnicole commented
oh oops the UI is confusing... i think i had to "Submit" my review to have you see all the comments.. do you see them now?

2022-04-27 19:45 UTC, morganee commented
> oh oops the UI is confusing... i think i had to "Submit" my review to have you see all the comments.. do you see them now?

yes ! thanks 👍

2022-04-29 21:00 UTC, morganee commented on components/atoms/FormInputWrapper.jsx
> +    position: 'absolute',
To place the helper text right below the input. We add them by default to all the ValidXX component so I added them here too

2022-04-29 21:02 UTC, morganee commented on components/atoms/Icon.jsx
> +const Icon = ({ className, icon, prefix, fontSize, context, size, ...rest }) => {
It's not showing ? I added the mdx and stories file and the index file

2022-04-29 21:03 UTC, morganee commented on components/molecules/TablePaginationFooter.jsx
> +    handleSizeChange: PropTypes.func,
yes thanks I'll update

2022-04-29 21:14 UTC, morganee commented on _stories/molecules/TablePaginationFooter/TablePaginationFooter.mdx
> +`handlePageChange` and `handleSizeChange` are used to update the table data to reflect the pagination state.
done

2022-04-29 21:14 UTC, mnicole commented on components/atoms/Icon.jsx
> +const Icon = ({ className, icon, prefix, fontSize, context, size, ...rest }) => {
it has ToolTipIcon but not Icon... btw you can see the build here https://deploy-preview-104--gumdrops.netlify.app/
anyway it's fine to finish this after your vacation :)

2022-05-24 12:21 UTC, morganee commented on components/atoms/Icon.jsx
> +const Icon = ({ className, icon, prefix, fontSize, context, size, ...rest }) => {
It's added. They were ignored by git because Icon was in the .gitignore as a default for Mac's

2022-05-25 05:03 UTC, mnicole approved these changes

2022-05-25 09:38 UTC, merged

2022-05-25 15:17 UTC, garrettbear commented
Sorry I just saw your updated commit and all looks good. Thanks for doing this!